AllCops:
  Exclude:
    # Исключаем все файлы в каталоге spec
    - 'spec//*'

Style/Documentation:
  # Отключаем проверку на наличие документации
  Enabled: false

Style/SymbolProc:
  # Отключаем проверку на использование Symbol#to_proc
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  # Отключаем проверку на наличие пустой строки после магических комментариев
  Enabled: false

Layout/EndOfLine:
  # Отключаем проверку на символ конца строки
  Enabled: false

Layout/TrailingEmptyLines:
  # Отключаем проверку на наличие пустых строк в конце файла
  Enabled: false

Metrics/BlockLength:
  Exclude:
    # Исключаем все файлы в каталоге spec из проверки длины блоков
    - 'spec//*'
    -

Style/StringLiterals:
  # Отключаем проверку на использование одинарных или двойных кавычек для строк
  Enabled: false
